### PR TITLE
Particle_P1: Add a small keep out dot

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
I've received the modules. They have a small dot connected to ground.

imagen
imagen

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Are you sure that this "dot" should not be grounded? Is it 100% ok to have a keepout there rather than a connection?

**Comment by antoniovazquezblanco** [comment]
That dot is connected to ground internally in the module. I can confirm that the module works without soldering that pin and I have not seen any reference that pointed to us having to solder that dot.

I would say that you can perfectly run any line there but no via or exposed copper should be placed there.

The eagle file for this component provided by particle does not connect that dot.

Thank you.

**Comment by SchrodingersGat** [comment]
Ok thanks

**Comment by antoniovazquezblanco** [comment]
Thank you for your time ;)

**Pull request merged**
