### PR TITLE
Add RFM69HW radio module footprint

### PR DESCRIPTION
**Pull request by MatthewStephenson**
Add RFM69HW radio module footprint.

Datasheet: http://www.hoperf.com/upload/rf/RFM69HW-V1.3.pdf

image

Symbol PR: https://github.com/KiCad/kicad-library/pull/1728

As always, comments and suggestions welcome.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @MatthewStephenson as this is a MPN (manufacturer part number) naming scheme, please prefix the manufacturer name. e.g.

```
Hope_RFM69HW
```

I realise now that you will also need to update the footprint entry for the symbol which I have already merged, sorry about that.

Cheers

**Comment by MatthewStephenson** [comment]
Hi @SchrodingersGat - thanks for the feedback. I will add the MPN prefix as you suggest, but before I do, I wanted to check my understanding of the KLC on this subject, as I did debate whether to add the manufacturer and decided not to, based on the following line of the KLC:

Under Symbol Libraries -> Symbol Names:
"2. Add the manufacturer name if it is required to differentiate from other similar parts"

As there's only one manufacturer making RFM69 modules, and as there are other components in rfcom.lib without manufacturer names (e.g. NRF24L01, UL865) I decided it wasn't needed for differentiation, and so left it out.

So should all such components with only one manufacturer have their manufacturer name prefixed? Or should they have a prefix in the symbol library but not in the footprint library (as is the case with the Telit UL865)?

Thanks,

- Matthew

**Comment by SchrodingersGat** [comment]
The manufacturer prefix rule is usually only for *footprints*. e.g. Texas instruments might have a very particular version of a QFN-48 so it needs a prefix `Texas_MPN_QFN-28`. 

The reason is that footprints are (as far as possible) generic - they can be used for many symbols. So we try to enforce a generic naming scheme. However, not all footprints conform to this! To make it apparent where we deviate from our scheme and use the manufacturers scheme, we try to prefix the manufacturer name to the footprint name.

Does this make sense? You won't need to change the name of the symbol, only the footprint.

**Comment by MatthewStephenson** [comment]
Thanks @SchrodingersGat for the explanation - changed the name, but you beat this comment with the merge!

**Pull request merged**
