### PR TITLE
Adding Laird BL652 Bluetooth module

### PR DESCRIPTION
**Pull request by cepr**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the contrib. Here's the output of our check utility:
```
checking module: Bluetooth_Module_Laird_BL652
  Violating Rule 10.1
    Footprint name must match its filename. (.kicad_mod files).
      footprint name (in file) was 'Bluetooth_Module_Laird_BL652', but expected (from filename)
      'Laird_BL652'.

  Violating Rule 10.2
    Doc property contains a full description of footprint.
      Documentation was empty!

  Violating Rule 10.4
    Value has a height of 1mm, thickness of 0.15mm, is filled with footprint name and is placed on the
    fabrication layer.
      Contents of value label ('BL652') is different from module name 'Bluetooth_Module_Laird_BL652'!

  Violating Rule 10.5
    Reference designator has a height of 1mm or smaller if needed, thickness of 0.15mm and is placed on
    the silkscreen layer.
      Reference label is on layer 'F.Fab', but should be on layer F.SilkS or B.SilkS!
      Reference label is on layer 'F.Fab', but should be on layer F.SilkS or B.SilkS!
      Reference label has a height of 2mm (expected: <=1mm).
      Reference label has a width of 2mm (expected: <=1mm).

  Violating Rule 10.6
    Attributes is set to the appropriate value, see tooltip for more information.
      There are mode SMD-pads (39) than THT-pads (0), but the attribute is not set to 'smd', but 'pth'.
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
      pin1 was found at x=-5.625mm y=-4.9mm.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.
      Some courtyard line is not on the expected grid of 0.01mm (line: {'width': 0.05, 'start': {'y': 5,
      'x': 6.175}, 'end': {'y': 5, 'x': -7.825}, 'layer': 'F.CrtYd'}).
      Some courtyard line is not on the expected grid of 0.01mm (line: {'width': 0.05, 'start': {'y': -5,
      'x': 6.175}, 'end': {'y': 5, 'x': 6.175}, 'layer': 'F.CrtYd'}).
      Some courtyard line is not on the expected grid of 0.01mm (line: {'width': 0.05, 'start': {'y': -5,
      'x': -7.825}, 'end': {'y': -5, 'x': 6.175}, 'layer': 'F.CrtYd'}).
      Some courtyard line is not on the expected grid of 0.01mm (line: {'width': 0.05, 'start': {'y': -5,
      'x': -7.825}, 'end': {'y': 5, 'x': -7.825}, 'layer': 'F.CrtYd'}).
```

Again: Please try to follow https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention 

What should be done here:
1. Courtyard is around the whole thing (with 0.25mm offset to the pads/outline)
2. F.Fab contains the actual outline of the package (I think in your case that should e.g. lie ON the pads)
3. silkscreen should be visible AFTER assembly, i.e. is typically 0.XXmm offset from F.Fab. Also it should not overlay the pads (i.e. your silkscreen might be OK)
4. REFDES should be on F.Fab

Best,
JAN

Here are some examples:
2016-12-03 13_09_09-footprinteditor keine aktive bibliothek
hsov
htssop28

**Comment by cepr** [comment]
No more warning reported by the tool, could you check again please?

**Comment by jkriege2** [comment]
Nice work ... one proposal: I would make a silkscreen as this:
2016-12-29 16_24_37-footprinteditor keine aktive bibliothek

It is a bit closer to the actual outline and has a pin1-mark (see KLC).

What do you think?
JAN

**Comment by cepr** [comment]
This looks nice, although I would not put a silkscreen line on the left side as the module is supposed to be placed right against the PCB border for the antenna to work properly. Ideally there should also be a keepout area on the left of the module but I don't think it's possible on a module.

**Comment by jkriege2** [comment]
Hhmmmm ... you're right, but then if the silkscreen is outside the board it will ultimately also not get printed (it's outside the board ;-) .... on the other hand: maybe do the silkscreen then only on those parts that are for sure on the boards? i.e. at the bottom border at least as wide as pin1 is on the top ... and keep the pin1-mark on the top?

About the keepout: You're right ... maybe this could be addressed as a request to the developers? Until then: Maybe mark it on F.Fab with a text like "no routes here"??? Not ideal, but might help ... on the other hand: If you use such a component, you SHOULD read the datasheet and design notes ,-)

Best,JAN

**Comment by jkriege2** [comment]
looks good this way, please still change according to this PNG:
2017-01-08 20_08_43-footprint editor no active library

Then I'll merge!
Best,
JAN

**Comment by cepr** [comment]
Here we go:

screenshot from 2017-01-08 15-45-18

**Comment by cepr** [comment]
There is still a small problem: the module is called `BL652` but the footprint filter for the symbol is `Laird*BL652*`, which one do you want me to change?

**Comment by SchrodingersGat** [comment]
I would suggest renaming the footprint to Laird_BL652

Cheers

**Comment by cepr** [comment]
Done!

**Comment by jkriege2** [comment]
nice work!
thanks,
JAN

**Pull request merged**
