### PR TITLE
RF modules - Decawave: add DWM1000 module

### PR DESCRIPTION
**Pull request by sdalu**
http://www.decawave.com/sites/default/files/resources/dwm1000-datasheet-v1.3.pdf

### CODE REVIEW

**Comment by pointhi** [comment]
please fix KLC:

```
checking module: DWM1000
  Violating Rule 10.2
    Doc property contains a full description of footprint.
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
  Violating Rule 6.9
    Value and reference have a height of 1mm.
```

**Comment by sdalu** [comment]
I'm really new to electronic and kicad, so if things are still not right, you will need to give me more explanations to help me fix them

**Comment by pointhi** [comment]
You could use https://github.com/KiCad/kicad-library-utils to check against basic KLC errors:

```
checking module: DWM1000
  Violating Rule 6.4
    For surface-mount devices, footprint anchor is placed in the middle with respect to device lead
    ends. (IPC-7351).
```

Furthermore:
- Silk screen should be fully visible after assembly (the silk screen outline). You can add the module dimensions using the F.Fab layer.
- I think the pads are not correctly positioned. There are differences between the left and the right side as well as the datasheet

**Comment by sdalu** [comment]
- I still have 6.4 error, event thought it seems to me I have put it in the middle of the component (F.Fab), or should I have used F.CrtYd as reference?
- I checked the pads, I only saw that pad 9-16 where 0.03 mm lower than expected (fixed)
- what layer do you use to warn of an antena area?

**Comment by pointhi** [comment]
For 6.4 it seems like, only pad's are currenty used to determin positioning of the component
I used Dwgs.User/Cmts.User for annotations on the footprint

**Comment by sdalu** [comment]
Do you want me to put the positioning using the middle of the pads, or do I keep it as it is in the middle of the component?

Seems I'm not allowed to use Dwgs.User/Cmts.User in the footprint making, theses layer entries are greyed out in the footprint editor (same as *.Cu, *.User, Edge.Cuts, Margin)

**Comment by pointhi** [comment]
@CarlPoirier what do you think about the positioning?

Hm, Dwgs.User and Cmts.User was allowed in the past for footprints. You can still select them via the menu when clicking onto the text/line

**Comment by ghost** [comment]
Closing and re-opening to trigger Travis CI checks.

**Comment by ghost** [comment]
Posting image of footprint for reference.

image

**Comment by ghost** [comment]
Hi @sdalu 

Sorry your pull request has not been looked at for a while.  If you are still interested in contributing, please let us know.

There is now an agreed way to show keepout areas in footprints.  See this issue: https://github.com/KiCad/kicad-library/issues/1443#issuecomment-318027572

Also, you can ignore the Travis CI error about KLC rule 8.2.  The automated check uses pad position to approximate the centre of the footprint, which doesn't work for asymmetric footprints like this :smile: 

The KLC and associated FAQ have been updated since your PR was opened.  Please check your footprint  against the latest version.  Not everything gets looked by the automated checks

https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention

**Comment by SchrodingersGat** [comment]
Hi @sdalu any interest in reviving this PR? :)

**Comment by sdalu** [comment]
No immediate interest. I'm closing it.

**Comment by bastinat0r** [comment]
I'm still interested, so I will have a go at it – however I am new to designing library parts myself, so no guaranties ;)

**Comment by bastinat0r** [comment]
I managed to add the right Ref value in the Fab-layer so the only errors I get by the KLC-Check are the missing 3D-Model and wrong location of the footprint-anchor. See the changes at https://github.com/bastinat0r/RF_Modules.pretty

PS: Do I need to create a new PR, or can I somehow update this one?

**Comment by sdalu** [comment]
Don't know if it's the right way to do it, I merged your changed to my branch and reopened the pull-request.

**Comment by crnorris** [comment]
Hi I'd like to use this module, is there anything I can do to help get it merged?

**Comment by SchrodingersGat** [comment]
Looks good, the KLC error can be ignored here. Thanks everyone.

**Pull request merged**
