### PR TITLE
Particle_P1: Add footprint

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Datasheet: https://docs.particle.io/datasheets/p1-datasheet/

imagen

Any suggestions?
Thanks!

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Forgot the keepout. Doing it...

**Comment by antoniovazquezblanco** [comment]
imagen

**Comment by SchrodingersGat** [comment]
Thanks for your contribution :)

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
