### PR TITLE
Add Digi XBee SMT module

### PR DESCRIPTION
**Pull request by svheymann**
One important question before a merge is possible:
I need to define a keepout-area below the module because there are 3 bare copper testpoints on the bottom side of the module. How do i do that?

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
There is not yet provision for keepouts to be specified in the footprints themselves. 

[Reference](https://bugs.launchpad.net/kicad/+bug/1513588)

For now, I would draw it on a graphical-only layer such as Dwgs.User and add the word "Keepout" in the middle of the area.

**Comment by svheymann** [comment]
done.

**Comment by SchrodingersGat** [comment]
That looks good. A few things to update:

1. Set "SMT" attribute -> Under footprint properties this is either called "Normal+Insert" or "Surface Mount" (depending on the version of KiCAD you are running)
1. Move the "doc" field to the "keywords" field
1. Add a datashet link (pdf) to the "doc" field.
1. Set the "name" label (XBee_SMT) to the same value as the actual filename of the part

(Most of these changes were found quickly using out library checking tool which you can find [here](https://github.com/KiCad/kicad-library-utils)

**Comment by svheymann** [comment]
done. I promise to use that for future footprints :) Thanks for checking!

**Comment by SchrodingersGat** [comment]
Great work, thanks for the submission

**Pull request merged**
