### PR TITLE
Add MOD-nRF8001

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**

### CODE REVIEW

**Comment by ghost** [comment]
Hi @piotr-wiszowaty 

Could you please post an image of the footprint and a link to the datasheet.

Thanks

**Comment by piotr-wiszowaty** [comment]
Documentation:
https://www.olimex.com/Products/Modules/RF/MOD-nRF8001/

Picture:
mod-nrf8001

**Comment by ghost** [comment]
Thanks @piotr-wiszowaty 

Posting dimensions from the website for reference ...

image

**Comment by ghost** [comment]
Just a few review points ...

1. The two inner rows of THT pads are presumably for fitting pin headers so that the module can be used on a breadboard, which is why you have not included them in your footprint?

2.  The SMD pads for soldering the castellated contacts could be shorter inside the board than outside.  Example ...

image

3. The centre anchor should be calculated from the overall size of the module, not just the pads.  The whole footprint needs to move right by 340 mil.  This will give a Travis CI error which can be ignored.

4.  There is room to move the silkscreen outline closer to the fab outline.  That would bring it within the courtyard.  Example ...

image

5. I can't see anything in the website links to say if a keep-out zone is needed under the module, especially on the left hand side where the antenna is.  You may wish to add a zone with the comment "Caution - antenna" - see latest KLC 7.8 for details. This would be for information only, since KiCad does not enforce keep-out zones at present.

**Comment by piotr-wiszowaty** [comment]
1. Yes.
2. Done.
3. Done.
4. Done.
5. The Dwgs.User and Cmts.User layers are disabled in the layer selection tab so I cannot select them for drawing. How do I enable these layers?

**Comment by ghost** [comment]
Hi @piotr-wiszowaty Sorry for delay in replying.  Thanks for the changes.

> The Dwgs.User and Cmts.User layers are disabled in the layer selection tab so I cannot select them for drawing. How do I enable these layers?

The workaround is to draw the elements on an unused layer (e.g B.SilkS).  Then select each element, edit properties and select Dwgs.User or Cmts.User (they are enabled in the pulldown list).  Or, quicker, edit the file and search and replace B.SilkS with the appropriate layer.

**Comment by piotr-wiszowaty** [comment]
Keep-out zone added.

**Comment by ghost** [comment]
Many thanks.

**Pull request merged**
