### PR TITLE
Added ST_SPBTLE footprint

### PR DESCRIPTION
**Pull request by suzizecat**
Here comes the footprint related to PR KiCad/kicad-library#1302 .
It comes from [the module datasheet](http://www.st.com/content/ccc/resource/technical/document/datasheet/48/74/89/26/50/8d/4e/33/DM00184006.pdf/files/DM00184006.pdf/jcr:content/translations/en.DM00184006.pdf)

I placed the anchor at the center of the module with respect to the physical outlines but checking scripts seems to place it with respect to pads, which, here, is quite different... 

I'd like to know how should i indicate keepout area (is keepout on Courtyard layer good ? Is there a good practice that i don't know ?)

image

Best,
Julien

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the controbution:

- Please move the footprint anchor to the center between all pins (see errors reported by Travis
2017-03-08 22_03_01-created footprint library housings_lcc by yo3iti pull request 1 kicad_housi
- please move the KeepOut-drawing to the layer Dwgs.User as done for other RF mocules:
2017-06-14 07_08_09-footprint editor no active library
- please move symbol name:
2017-06-14 07_11_52-footprint editor no active library

Otherwise: Very nice work!

JAN

**Comment by suzizecat** [comment]
I moved things like you recommended. BTW is there a rule i may have missed for the symbol name placement ? Since it fit into the component outline and it's for fabrication only, i thought it might be more convenient to put it inside the component outline.

Thanks for your help !

**Comment by suzizecat** [comment]
No one for this footprint ? :sob:

**Comment by SchrodingersGat** [comment]
@suzizecat I'll check it out soon :) Sorry!

**Comment by suzizecat** [comment]
Yay ! Thanks a lot 😄

**Comment by SchrodingersGat** [comment]
Thanks for the contribution :)

**Pull request merged**
