### PR TITLE
Added Linx_RXM_GPS family footprint

### PR DESCRIPTION
**Pull request by suzizecat**
Here comes the footprint for the Linx GPS of PR KiCad/kicad-library#1301
Created from datasheet [RXM-GPS-RM](https://linxtechnologies.com/wp/wp-content/uploads/rxm-gps-rm.pdf)
image

I have a doubt about how to tell that there is a keepout area on the top layer and it should be a GND plane on the bottom side... Here, it's on the top courtyard layer. If there is a better way to do it, please let me know.

### CODE REVIEW

**Comment by suzizecat** [comment]
Hello there !
No one for the GPS stuff ? 😭

**Comment by SchrodingersGat** [comment]
This looks mostly good but looking at the datasheet, it appears that the two central pads should be **0.5 x 0.92mm** (you have them as **0.5 x 0.7mm**.

Is there a reason for this difference?

**Comment by suzizecat** [comment]
Damn, they are vicious ! On the drawing in the datasheet, those pads looks exactly the same width as the others, so i didn't paid attention.
I'll update that right away

**Comment by SchrodingersGat** [comment]
Thanks for the contribution :)

**Pull request merged**
