### PR TITLE
Added xL865

### PR DESCRIPTION
**Pull request by suzizecat**
I just made a FP for Telit xL865 series GSM modules.
It have a 1.5mm Courtyard clearance as it's recommended in the DS, but since it's for mounting purpose, i don't really know if it should stay like this or if it should be reduced to 0.25mm as stated in KLC.

You'll find the DS here : http://www.telit.com/fileadmin/user_upload/products/Downloads/3G/Telit_UL865_Hardware_User_Guide_r8.pdf

And here are the pics : 

image

image

### CODE REVIEW

**Comment by suzizecat** [comment]
I just saw i forgot the pin renumbering. I'll fix that right away

**Comment by poeschlr** [comment]
I would leave the courtyard at the current position. (Datasheet trumps KLC)

The chamfer on silk would be below the part. (Silk below the part creates problems for reflow soldering)
The pin 1 marker on silk should also be visible after assembly.
(Have a look at the qfn footprints for inspiration)

Maybe also increase the clearance between pads an silk? I would suggest you make sure that silk is outside the recommended mask clearance of 0.15mm. Or maybe give a bit extra for tolerances. (I normally use 0.2mm pad to silk clearance)

**Comment by suzizecat** [comment]
I didn't know that silkscreen could be a problem for the placement.

I added the pin 1 marker accordingly to https://www.cskl.de/fileadmin/downloads/PCBLIBRARIES/Documentation/What-is-New-in-IPC-7351C_.pdf (page 15) which i believe present the right IPC standard...

image

**Comment by poeschlr** [comment]
What about the pin 1 marker on the fab layer? (your screenshot detail does not look like it has one)

**Comment by suzizecat** [comment]
Its the silkscreen line which follow the pad (it goes along pad 1 but not pad 48) as i said : 
 >I added the pin 1 marker accordingly to https://www.cskl.de/fileadmin/downloads/PCBLIBRARIES/Documentation/What-is-New-in-IPC-7351C_.pdf (page 15) which i believe present the right IPC standard...

**Comment by poeschlr** [comment]
Silkscreen is ok what about the fabrication layer (the yellow layer)
Or is your screenshot not up do date? (I did not look at the footprint it self only at your last screenshot)

**Comment by suzizecat** [comment]
Oh sorry, misread 😅 
This is the only corner which is "straight" corner (look at the first screen capture) as is the physical module outline. 
BTW Should i transform the rounded corners and make them "straight" (and/or add a proper pin 1 marker) ?

**Comment by poeschlr** [comment]
Sorry for the delay.
I think it is ok now. Thanks for contributing.

**Comment by suzizecat** [comment]
Thanks for the review 😉

**Pull request merged**
