### PR TITLE
RF Modules - SIGFOX: Add TD1205 and TD1208 modules

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Add TD1205 and TD1208 SIGFOX modules

### CODE REVIEW

**Comment by pointhi** [comment]
```
checking module: TD1205
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 6.4
    For surface-mount devices, footprint anchor is placed in the middle with respect to device lead
    ends. (IPC-7351).
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
checking module: TD1208
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
```

**Comment by myfreescalewebpage** [comment]
Seems I have forgotten to check KLC issues before commit. Sorry for inconvenient.
All issues fixed.

**Comment by pointhi** [comment]
- Please check the positioning of the pads
- You can mark the No routing area / antenna using `Dwgs.User`
- Please add a drawing of the outline using F.Fab

**Comment by myfreescalewebpage** [comment]
Done.
No routing area is grey out in my Kicad... How to use it ? See screnshots below.
TD1208 violating 6.4 but I do not understand why because the anchor is at the center.... If you can help me I would appreciate.

td1205
td1208

**Comment by ghost** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by ghost** [comment]
Hi @myfreescalewebpage Sorry for the delay in coming back to review this PR.

> TD1208 violating 6.4 but I do not understand why because the anchor is at the center.... If you can help me I would appreciate.

The KLC check scripts use a bounding box around the pads as a heuristic to determine the centre of the device.  This **usually** works but not always :wink: as in this case where the pads are not symmetric about the centre of the device body.  You can ignore that KLC error.

If you would still like to submit this, please look at the other KLC errors (https://travis-ci.org/KiCad/RF_Modules.pretty/builds/249611285?utm_source=github_status&utm_medium=notification) and fix them or come back with questions.  

Many thanks

**Comment by ghost** [comment]
Closing inactive PR.

**Pull request closed without merging**
